name: inception

services:
    nginx:
        depends_on:
            - wordpress
        build: ./nginx
        image: "nginx"
        restart: on-failure
        ports:
            - 443:80
        volumes:
            - wp:/var/www/html
        networks:
            - services-network

    wordpress:
        depends_on:
            mariadb:
                condition: service_healthy
        build: ./wordpress/
        image: "wordpress"
        env_file: .env
        restart: on-failure
        volumes:
            - wp:/var/www/html
        secrets:
            - wp_db_psswd
            - wp_admin_psswd
            - wp_user_psswd
        networks:
            - services-network

    mariadb:
        build: ./mariadb/
        image: "mariadb"
        healthcheck:
            test: ["CMD", "mariadb-admin", "ping" ]
            interval: 10s
            retries: 2
            start_period: 10s
        env_file: .env
        restart: on-failure
        volumes:
            - db:/var/lib/mysql
        secrets:
            - db_root_psswd
            - wp_db_psswd
        networks:
            - services-network

volumes:
    db:
        # driver_opts:
            # device: C:\Users\dell\Desktop\volume
    wp:

secrets:
    db_root_psswd:
        file: ../secrets/db_root_psswd.txt
    wp_db_psswd:
        file: ../secrets/wp_db_psswd.txt
    wp_admin_psswd:
        file: ../secrets/wp_admin_psswd.txt
    wp_user_psswd:
        file: ../secrets/wp_user_psswd.txt

networks:
    services-network:
        driver: bridge