name: inception

services:
    nginx:
        depends_on:
            - wordpress
        build: nginx/
        ports:
            - 443:80
        volumes:
            - wp:/var/www/html

    wordpress:
        depends_on:
            - mariadb
        build: wordpress/
        volumes:
            - wp:/var/www/html
        environment:
            WORDPRESS_DB_HOST: mariadb:3306
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wp
            WORDPRESS_DB_PASSWORD: wp_db_psswd
        secrets:
            - wp_db_psswd

    mariadb:
        build: mariadb/
        environment:
            MARIADB_ROOT_PASSWORD_FILE: db_root_psswd
            MARIADB_DATABASE: wordpress
            MARIADB_USER: wp
            MARIADB_PASSWORD_FILE: wp_db_psswd
        volumes:
            - db:/var/lib/mysql
        secrets:
            - db_root_psswd
            - wp_db_psswd

volumes:
    db:
        # driver_opts:
            # device: C:\Users\dell\Desktop\volume
    wp:

secrets:
    db_root_psswd:
        file: ../secrets/db_root_psswd.txt
    wp_db_psswd:
        file: ../secrets/wp_db_psswd.txt