name: inception

services:
    nginx:
        depends_on:
            - wordpress
        build: ./requirements/nginx
        image: "nginx:1337"
        restart: on-failure:3
        ports:
            - 443:80
        volumes:
            - wp:/var/www/html
        networks:
            - services-network

    wordpress:
        depends_on:
            redis:
                condition: service_started
            mariadb:
                condition: service_healthy
        build: ./requirements/wordpress/
        image: "wordpress:1337"
        env_file: .env
        restart: on-failure:3
        volumes:
            - wp:/var/www/html
        secrets:
            - wp_db_psswd
            - wp_admin_psswd
            - wp_user_psswd
        networks:
            - services-network

    mariadb:
        build: ./requirements/mariadb/
        image: "mariadb:1337"
        healthcheck:
            test: mariadb-admin -u root -p$(cat /run/secrets/db_root_psswd) ping
            start_period: 30s
            start_interval: 30s
        env_file: .env
        restart: on-failure:3
        volumes:
            - db:/var/lib/mysql
        secrets:
            - db_root_psswd
            - wp_db_psswd
        networks:
            - services-network
    
    redis:
        build: ./requirements/bonus/redis/
        image: "redis:1337"
        restart: on-failure:3
        networks:
            - services-network

    ftp:
        build: ./requirements/bonus/ftp/
        image: "ftp:1337"
        ports:
            - 21:21
            - 3000-3010:3000-3010
        restart: on-failure:3
        volumes:
            - wp:/home/ftp_client/
        secrets:
            - ftp_client_psswd
        networks:
            - services-network
            
    adminer:
        depends_on:
            - mariadb
        build: ./requirements/bonus/adminer/
        image: "adminer:1337"
        ports:
            - 7000:80
        restart: on-failure:3
        networks:
            - services-network
    
    cadvisor:
        build: ./requirements/bonus/cadvisor/
        image: "cadvisor:1337"
        ports:
            - 8080:8080
        restart: on-failure:3
        networks:
            - services-network
        volumes:
            - /var/lib/docker/:/var/lib/docker:ro
            - /sys:/sys:ro
            - /var/run:/var/run:rw
            - /:/rootfs:ro

    website:
        build: ./requirements/bonus/website/
        image: "website:1337"
        ports:
            - 7070:7070
        restart: on-failure:3
        networks:
            - services-network

volumes:
    db:
        driver_opts:
            type: none
            device: /home/mlouazir/data/db
            o: bind
    wp:
        driver_opts:
            type: none
            device: /home/mlouazir/data/wp
            o: bind

secrets:
    db_root_psswd:
        file: ../secrets/db_root_psswd.txt
    wp_db_psswd:
        file: ../secrets/wp_db_psswd.txt
    wp_admin_psswd:
        file: ../secrets/wp_admin_psswd.txt
    wp_user_psswd:
        file: ../secrets/wp_user_psswd.txt
    ftp_client_psswd:
        file: ../secrets/ftp_client_psswd.txt

networks:
    services-network:
        driver: bridge