name: inception

services:
    nginx:
        depends_on:
            - wordpress
        build: ./nginx
        image: "nginx"
        ports:
            - 443:80
        volumes:
            - wp:/var/www/html

    wordpress:
        depends_on:
            mariadb:
                condition: service_healthy
        build: ./wordpress/
        env_file: .env
        # healthcheck:
            # test: ["CMD", "wp db check", "--allow-root" ]
            # interval: 1m30s
            # timeout: 30s
            # retries: 5
            # start_period: 30s
        volumes:
            - wp:/var/www/html
        secrets:
            - wp_db_psswd
            - wp_admin_psswd
            - wp_user_psswd

    mariadb:
        build: ./mariadb/
        healthcheck:
            test: ["CMD", "mariadb-admin", "ping" ]
            interval: 10s
            retries: 2
            start_period: 10s
        env_file: .env
        volumes:
            - db:/var/lib/mysql
        secrets:
            - db_root_psswd
            - wp_db_psswd

volumes:
    db:
        # driver_opts:
            # device: C:\Users\dell\Desktop\volume
    wp:

secrets:
    db_root_psswd:
        file: ../secrets/db_root_psswd.txt
    wp_db_psswd:
        file: ../secrets/wp_db_psswd.txt
    wp_admin_psswd:
        file: ../secrets/wp_db_psswd.txt
    wp_user_psswd:
        file: ../secrets/wp_db_psswd.txt