name: inception

services:
    nginx:
        depends_on:
            - wordpress
        image: "nginx"
        build: ./nginx
        ports:
            - 443:80
        volumes:
            - wp:/var/www/html

    wordpress:
        depends_on:
            - mariadb
        build: ./wordpress/
        # image: "nginx:ll2"
        volumes:
            - wp:/var/www/html
        # secrets:
        #     - wp_db_psswd

    mariadb:
        build: ./mariadb/
        # image: "nginx:ll3"
        volumes:
            - db:/var/lib/mysql
        # secrets:
        #     - db_root_psswd
        #     - wp_db_psswd

volumes:
    db:
        # driver_opts:
            # device: C:\Users\dell\Desktop\volume
    wp:

secrets:
    db_root_psswd:
        file: ../secrets/db_root_psswd.txt
    wp_db_psswd:
        file: ../secrets/wp_db_psswd.txt